[mypy]
exclude = (?x)(/fixtures/|/larkparse/|/vendor/|/scripts/|jac/examples/reference)
mypy_path = jac:jac-byllm:jac-client:jac-streamlit

[mypy-jaclang.vendor.*]
ignore_errors = True

[mypy-jaclang.pycore.parser.larkparse.*]
follow_imports = skip
ignore_errors = True
