// Auto-generated by jac build --client react-native. Do not edit.
// To customize the root shell, edit app/App.tsx instead.
import 'react-native-gesture-handler';
import { registerRootComponent } from 'expo';
import App from './app/App';

registerRootComponent(App);
